### ISSUE TITLE
Cabal projects recognition while cabal sandboxes used

### ISSUE THREAD

**Issue by sinevar** [chaika2013/ide-haskell#27]
I cannot get auto detection of cabal project working out of the box on my MacOS Mavericks. (Used cabal sandbox init)

Every time I open or drag the cabal sandbox project into Atom, I also need to go to packages, search for Ide Haskell and afterwords disable&enable it. Doing so, I can benefit from almost all the features from this extension.

However I couldn't make the autocompletion working. I have autocomplete plus, but Ide Haskell is not reacting at all while I'm typing 'import' or '{-# LANGUAGES...

How is the list for autocompletion generated? Via ghc-mod list ?

Any ideas how I can track the errors/problems of it?

**Comment by lierdakil** [comment]
So, does 0.3.1 fix these bugs? I can't replicate them, but that may be because I lack information.

**Comment by lierdakil** [comment]
Closing as there are no reports that this bug persists.
