### ISSUE TITLE
mousemove is fired even if mouse is standing still, causing type checking to blink

### ISSUE THREAD

**Issue by jannickj** [chaika2013/ide-haskell#44]
When I updated to all the newest versions of both ide-haskell and atom I had a really annoying flicker on the type checking.

I managed to track it down to 
edditor-control.coffee where the mousemove event was being fired even if the mouse wasn't moving
i made a dirty but effective fix

    # show expression type if mouse stopped somewhere
    @lastpixelpos = {top:0, left:0}
    @subscriber.subscribe @scroll, 'mousemove', (e) =>
      @newpixelpos = pixelPositionFromMouseEvent(@editor, e)
      if not (@lastpixelpos.top == @newpixelpos.top && @lastpixelpos.left == @newpixelpos.left)
        @lastpixelpos = @newpixelpos
        @clearExprTypeTimeout()
        @exprTypeTimeout = setTimeout (=>
          @showExpressionType e
        ), atom.config.get('ide-haskell.expressionTypeInterval')
    @subscriber.subscribe @scroll, 'mouseout', (e) =>
      @clearExprTypeTimeout()

**Comment by lierdakil** [comment]
Is this bug Windows-specific? I can't seem to reproduce on Linux.

**Comment by jannickj** [comment]
I think it is specific to windows I didn't get it on my arch linux, however i think its an overall safe thing to check anyway.
